version: '3'

services:
  app:
    image: stacked-fourside:latest
    build:
      context: .
      args:
        - base_url=${BASE_URL}
    environment:
      HOST: "0.0.0.0:4321"
      DATABASE_URL: "postgresql://postgres:fourside@db/"
      STACKED_FOURSIDE_HOST: ${BASE_URL}
    ports:
      - "4321:4321"
    depends_on:
      - db
  db:
    image: postgres:15
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=fourside
      - POSTGRES_DB=stacked-fourside
