//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "game")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub state: Json,
    pub player_one_id: Option<i32>,
    pub player_two_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::player::Entity",
        from = "Column::PlayerOneId",
        to = "super::player::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Player2,
    #[sea_orm(
        belongs_to = "super::player::Entity",
        from = "Column::PlayerTwoId",
        to = "super::player::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Player1,
}

impl ActiveModelBehavior for ActiveModel {}
