//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "game")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub squares: Json,
    pub player_red_id: Option<i32>,
    pub player_black_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::player::Entity",
        from = "Column::PlayerRedId",
        to = "super::player::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PlayerRed,
    #[sea_orm(
        belongs_to = "super::player::Entity",
        from = "Column::PlayerBlackId",
        to = "super::player::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PlayerBlack,
}

impl ActiveModelBehavior for ActiveModel {}
